/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.m3.training.inventory;

import org.junit.Test;

import com.m3.training.inventory.Library;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    

    
}
